// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Paymentstatus string

const (
	PaymentstatusPENDING Paymentstatus = "PENDING"
	PaymentstatusSUCCESS Paymentstatus = "SUCCESS"
	PaymentstatusFAILED  Paymentstatus = "FAILED"
)

func (e *Paymentstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Paymentstatus(s)
	case string:
		*e = Paymentstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Paymentstatus: %T", src)
	}
	return nil
}

type NullPaymentstatus struct {
	Paymentstatus Paymentstatus `json:"paymentstatus"`
	Valid         bool          `json:"valid"` // Valid is true if Paymentstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Paymentstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Paymentstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Paymentstatus), nil
}

type Payment struct {
	ID        uuid.UUID          `json:"id"`
	Amount    decimal.Decimal    `json:"amount"`
	Currency  string             `json:"currency"`
	Reference string             `json:"reference"`
	Status    Paymentstatus      `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
