package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"net/http"
	"os"
	"pgm/internal/domain"
	pmt "pgm/internal/handler/payment"
	q "pgm/internal/queue"
	"pgm/internal/repo"
	"pgm/internal/repo/db"
	"pgm/internal/service"
	"time"

	"github.com/golang-migrate/migrate/v4"
	"github.com/golang-migrate/migrate/v4/database/postgres"

	_ "pgm/app/api/docs" // docs is generated by Swag CLI, you have to import it.

	_ "github.com/golang-migrate/migrate/v4/source/file"
	_ "github.com/jackc/pgx/v5/stdlib"
	echoSwagger "github.com/swaggo/echo-swagger"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

// @title Payment Gateway Module API
// @version 1.0
// @description This is a payment gateway module with Swagger documentation.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /v1

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
func main() {
	// Database
	dsn := fmt.Sprintf("postgres://%s:%s@%s:%s/%s?sslmode=disable", os.Getenv("DB_USER"), os.Getenv("DB_PASSWORD"), os.Getenv("DB_HOST"), os.Getenv("DB_PORT"), os.Getenv("DB_NAME"))
	pool, err := repo.NewPool(context.Background(), dsn)
	if err != nil {
		log.Fatalf("failed to connect to database: %v", err)
	}
	defer pool.Close()

	// Run migrations
	if err := runMigrations("file:///app/internal/repo/schema", os.Getenv("DB_NAME"), dsn); err != nil {
		log.Fatalf("failed to run migrations: %v", err)
	}

	// RabbitMQ Publisher
	publisher, err := q.NewRabbitMQPublisher()
	if err != nil {
		log.Fatalf("failed to connect to rabbitmq: %v", err)
	}
	// Note: In a real app, we'd handle closing the publisher gracefully

	// Repository
	queries := db.New(pool)

	// service
	uc := service.NewPaymentService(queries, pool, publisher)

	// Echo
	e := echo.New()

	// Middleware
	e.Use(middleware.RequestLogger())
	e.Use(middleware.Recover())
	e.Use(middleware.TimeoutWithConfig(middleware.TimeoutConfig{
		Timeout:      time.Minute,
		ErrorMessage: "Request timeout",
	}))

	e.HTTPErrorHandler = domain.ErrorHandler

	// API v1 group
	g := e.Group("/v1")

	// Swagger documentation
	e.GET("/swagger/*", echoSwagger.WrapHandler)
	srv := &http.Server{
		Addr:         ":8080",
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	// Handlers
	pmt.NewPaymentHandler(g, uc)

	// Start server
	e.StartServer(srv)
}

// RunMigrations automatically applies migrations on startup.
func runMigrations(filePath, dbname string, dsn string) error {
	log.Println("Running migrations...")
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		log.Fatalf("Failed to open temp DB for migrations: %v", err)
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		log.Fatalf("Failed to ping temp DB for migrations: %v", err)
	}

	// 2. Create a new "postgres" driver instance for migrate
	driver, err := postgres.WithInstance(db, &postgres.Config{})
	if err != nil {
		log.Fatalf("Failed to create migrate driver instance: %v", err)
	}

	// 3. Create the migrate instance
	// Point to your migrations directory
	m, err := migrate.NewWithDatabaseInstance(
		filePath, // Source URL
		dbname,   // Database name
		driver,   // The driver instance
	)
	if err != nil {
		log.Fatalf("Failed to create migrate instance: %v", err)
	}

	// 4. Run the migrations
	if err := m.Up(); err != nil && err != migrate.ErrNoChange {
		log.Fatalf("An error occurred while running migrations: %v", err)
	}

	log.Println("Migrations applied successfully!")
	return nil
}
